services:
  postgres:
    image: postgres:18.2
    container_name: progkorny-pg
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata: