spring.application.name=beadando
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/${POSTGRES_DB:beadando}
spring.datasource.username=${POSTGRES_USER:beadando}
spring.datasource.password=${POSTGRES_PASSWORD:beadando}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
