CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    brand VARCHAR(60) NOT NULL,
    plate_number VARCHAR(15) NOT NULL,
    type VARCHAR(10) NOT NULL,
    img_url VARCHAR(255),
    km INT NOT NULL,
    year_of_manufacture INT NOT NULL,
    color VARCHAR(40) NOT NULL,
    price INT NOT NULL,
    fuel VARCHAR(12) NOT NULL,
    condition_status VARCHAR(15) NOT NULL,
    status INT NOT NULL,
    description TEXT
);

CREATE TABLE features (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE vehicle_features (
    vehicle_id BIGINT NOT NULL,
    feature_id BIGINT NOT NULL,
    PRIMARY KEY (vehicle_id, feature_id),
    CONSTRAINT fk_vehicle_features_vehicle
        FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE,
    CONSTRAINT fk_vehicle_features_feature
        FOREIGN KEY (feature_id) REFERENCES features (id) ON DELETE CASCADE
);
