CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    plate_number VARCHAR(15) NOT NULL,
    type VARCHAR(10) NOT NULL,
    img_url VARCHAR(255),
    km INT NOT NULL,
    year_of_manufacture INT NOT NULL,
    color VARCHAR(40) NOT NULL,
    fuel VARCHAR(12) NOT NULL,
    condition_status VARCHAR(15) NOT NULL,
    status INT NOT NULL,
    description TEXT
);
