CREATE TABLE users (
                       id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(80)  NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role     VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER'
);

ALTER TABLE vehicles ADD COLUMN user_id BIGINT;
ALTER TABLE vehicles ADD CONSTRAINT fk_vehicle_user
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;

-- seed one admin so you can log in immediately
INSERT INTO users (username, password, role)
VALUES ('admin', '$2a$12$QdCpDbaxijQqHvIDF7gpgOSOuA66ddZT5whv23a260QQa2dlhQApi', 'ROLE_ADMIN');
-- password above is: admin123  (bcrypt hash)