name: build

on:
  push:
    branches: [ "gombi" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18.2
        env:
          POSTGRES_DB: beadando
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Start Artifactory
        run: docker run -d --name artifactory -p 8081:8081 releases-docker.jfrog.io/jfrog/artifactory-oss:latest

      - name: Wait for services
        run: sleep 180

      - name: Create Maven settings
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>artifactory</id>
                <username>admin</username>
                <password>password</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build & Deploy
        run: mvn -B -DskipTests deploy